using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading;
using CharacterViewer.Rendering;
using Mutagen.Bethesda.Plugins;
using Newtonsoft.Json.Linq;
using NPC_Plugin_Chooser_2.Models;

namespace NPC_Plugin_Chooser_2.BackEnd.CharacterViewerHost;

/// <summary>
/// Unified renderer-aware staleness check for mugshots. Implements the
/// two-tier policy:
///
/// <list type="number">
/// <item>Was this PNG produced by the user's currently-active renderer? If
/// not (Internal vs LegacyPortraitCreator mismatch), it's stale regardless
/// of any other comparison — switching renderers should drop the previous
/// renderer's outputs.</item>
/// <item>For the active renderer, version-and-settings drift gates: Internal
/// compares <see cref="CharacterViewerRendering.Version"/> + a hash of the
/// relevant <see cref="InternalMugshotSettings"/>; Legacy delegates to
/// <see cref="PortraitCreator.NeedsRegeneration"/> (program version,
/// NIF SHA, background, lighting, etc.).</item>
/// </list>
///
/// Only PNGs that carry a "Parameters" tEXt chunk are considered for
/// regeneration — hand-crafted user mugshots without metadata are left
/// alone, matching the legacy behavior.
/// </summary>
public sealed class MugshotStalenessChecker
{
    private readonly Settings _settings;
    private readonly PortraitCreator _legacy;

    public MugshotStalenessChecker(Settings settings, PortraitCreator legacy)
    {
        _settings = settings;
        _legacy = legacy;
    }

    /// <summary>
    /// Decides whether <paramref name="pngPath"/> needs to be regenerated by
    /// the currently-active renderer.
    /// </summary>
    /// <param name="pngPath">Path to the existing mugshot PNG.</param>
    /// <param name="npcFormKey">FormKey of the NPC the PNG depicts (used for
    /// the Internal renderer's settings-hash check).</param>
    /// <param name="legacyNifPath">FaceGen NIF path — only consulted when the
    /// active renderer is Legacy. Pass null/empty for Internal callers.</param>
    /// <param name="legacyDataFolders">Mod data folders — only consulted when
    /// the active renderer is Legacy. Pass null for Internal callers.</param>
    /// <param name="legacyAutoGenerated">Auto-generated-mod flag forwarded
    /// to <see cref="PortraitCreator.NeedsRegeneration"/>.</param>
    public bool NeedsRegeneration(
        string pngPath,
        FormKey npcFormKey,
        string? legacyNifPath = null,
        IEnumerable<string>? legacyDataFolders = null,
        bool legacyAutoGenerated = false)
    {
        var sw = Stopwatch.StartNew();
        int tid = Environment.CurrentManagedThreadId;
        string fileLabel = string.IsNullOrEmpty(pngPath) ? "(empty)" : Path.GetFileName(pngPath);
        Trace($"ENTER tid={tid} npc={npcFormKey} png={fileLabel}");

        // Missing file = always stale (caller should treat as "generate fresh").
        if (string.IsNullOrWhiteSpace(pngPath) || !File.Exists(pngPath))
        {
            Trace($"EXIT tid={tid} png={fileLabel} result=STALE(missing) elapsed={sw.ElapsedMilliseconds}ms");
            return true;
        }

        var json = MugshotPngMetadata.TryRead(pngPath);
        Trace($"  metadata-read tid={tid} png={fileLabel} hasParams={json != null} elapsed={sw.ElapsedMilliseconds}ms");
        if (json == null)
        {
            // No "Parameters" chunk — treat as a hand-placed mugshot. Legacy's
            // NeedsRegeneration also returns false in this case.
            Trace($"EXIT tid={tid} png={fileLabel} result=FRESH(no-params) elapsed={sw.ElapsedMilliseconds}ms");
            return false;
        }

        var pngRenderer = DetectRenderer(json);

        // Tier 1: cross-renderer staleness. If the PNG came from a different
        // renderer than the user has selected, regenerate.
        if (pngRenderer != _settings.SelectedRenderer)
        {
            Trace($"  Tier1 renderer mismatch png={pngRenderer} active={_settings.SelectedRenderer}");
            Trace($"EXIT tid={tid} png={fileLabel} result=STALE(renderer-mismatch) elapsed={sw.ElapsedMilliseconds}ms");
            return true;
        }

        // Tier 2: per-renderer staleness.
        bool result = _settings.SelectedRenderer switch
        {
            MugshotRenderer.Internal => InternalNeedsRegeneration(json),
            MugshotRenderer.LegacyPortraitCreator => _legacy.NeedsRegeneration(
                pngPath, legacyNifPath ?? string.Empty,
                legacyDataFolders ?? Array.Empty<string>(),
                legacyAutoGenerated),
            _ => false,
        };
        Trace($"EXIT tid={tid} png={fileLabel} active={_settings.SelectedRenderer} result={(result ? "STALE" : "FRESH")} elapsed={sw.ElapsedMilliseconds}ms");
        return result;
    }

    private static void Trace(string message)
    {
        // Both Debug and Trace listeners receive these — Debug captures in
        // VS output for unattached runs; Trace also flows to attached
        // diagnostic listeners (e.g. DebugView) without recompile.
        Debug.WriteLine($"[StalenessChecker] {message}");
        System.Diagnostics.Trace.WriteLine($"[StalenessChecker] {message}");
    }

    /// <summary>
    /// Reads the "renderer" field from the metadata JSON and maps it to a
    /// <see cref="MugshotRenderer"/>. Legacy PNGs (which predate the field)
    /// are reported as <see cref="MugshotRenderer.LegacyPortraitCreator"/>.
    /// </summary>
    private static MugshotRenderer DetectRenderer(string parametersJson)
    {
        try
        {
            var token = JToken.Parse(parametersJson);
            string? renderer = (token as JObject)?["renderer"]?.Value<string>();
            if (string.Equals(renderer, InternalMugshotMetadata.RendererName, StringComparison.OrdinalIgnoreCase))
            {
                return MugshotRenderer.Internal;
            }
        }
        catch
        {
            // Malformed JSON — fall through to Legacy assumption.
        }
        return MugshotRenderer.LegacyPortraitCreator;
    }

    private bool InternalNeedsRegeneration(string parametersJson)
    {
        JObject? root;
        try
        {
            root = JToken.Parse(parametersJson) as JObject;
        }
        catch (Exception ex)
        {
            Trace($"  Internal: JSON parse failed ({ex.Message}); treating as STALE");
            return true;
        }
        if (root == null)
        {
            Trace("  Internal: JSON root is not an object; treating as STALE");
            return true;
        }

        // Version drift (gated like the legacy path on AutoUpdateOldMugshots).
        if (_settings.AutoUpdateOldMugshots)
        {
            var pngVersionStr = root["renderer_version"]?.Value<string>();
            if (string.IsNullOrWhiteSpace(pngVersionStr) ||
                !Version.TryParse(pngVersionStr, out var pngVersion) ||
                pngVersion < CharacterViewerRendering.Version)
            {
                Trace($"  Internal: version drift png='{pngVersionStr}' current={CharacterViewerRendering.Version}");
                return true;
            }
        }

        // Settings drift (gated on AutoUpdateStaleMugshots).
        if (_settings.AutoUpdateStaleMugshots)
        {
            var pngHash = root["settings_hash"]?.Value<string>() ?? "";
            var currentHash = InternalMugshotMetadata.ComputeSettingsHash(_settings.InternalMugshot);
            if (!string.Equals(pngHash, currentHash, StringComparison.OrdinalIgnoreCase))
            {
                Trace($"  Internal: settings-hash drift png={pngHash[..Math.Min(8, pngHash.Length)]}.. current={currentHash[..Math.Min(8, currentHash.Length)]}..");
                return true;
            }
        }

        return false;
    }
}
