using System.Diagnostics;
using System.Windows.Media;
using Mutagen.Bethesda.Plugins;
using Newtonsoft.Json;

namespace NPC_Plugin_Chooser_2.Models;

[DebuggerDisplay("{DisplayName}")]
public class ModSetting
{
    public string DisplayName { get; set; } = string.Empty;
    public List<ModKey> CorrespondingModKeys { get; set; } = new();
    public List<string> CorrespondingFolderPaths { get; set; } = new(); // first should be the base mod, and others are overrides where the program should find conflict winning data if it exists
    public string MugShotFolderPath { get; set; } = string.Empty; // Path to the mugshot folder FOR THIS MOD SETTING
    public bool IsFaceGenOnlyEntry { get; set; } = false;
    public HashSet<FormKey> FaceGenOnlyNpcFormKeys { get; set; } = new();
    public bool IsAutoGenerated { get; set; } = false;
    public HashSet<FormKey> NpcFormKeys { get; set; } = new(); // All NPCs contained in this mod
    public Dictionary<FormKey, List<ModKey>> AvailablePluginsForNpcs { get; set; } = new(); // Maps all available CorrespondingModKeys that can be used as a source plugin for this ModSetting
    public HashSet<FormKey> AmbiguousNpcFormKeys { get; set; } = new(); // All NPCs with > 1 available plugins
    public Dictionary<FormKey, ModKey> NpcPluginDisambiguation { get; set; } = new(); // Maps NPC FormKey to the ModKey from which it should inherit data, specifically for NPCs appearing in multiple plugins within this ModSetting.
    public Dictionary<FormKey, string> NpcFormKeysToDisplayName { get; set; } = new();

    public bool MergeInDependencyRecords { get; set; } = true;
    [JsonIgnore] 
    public static string DefaultMergeInTooltip =
        "If checked, all records needed by the mod will be merged into the output." +
        Environment.NewLine + "The output plugin will no longer depend on them as masters." +
        Environment.NewLine + "Only masters found within this mod's Mod Folders will be merged in." +
        Environment.NewLine + "Do not merge in records from plugins that are going to be kept in your load order.";
    
    public string MergeInToolTip { get; set; } = DefaultMergeInTooltip;
    public SolidColorBrush MergeInLabelColor { get; set; } = new (Colors.Black);
    public RecordOverrideHandlingMode? ModRecordOverrideHandlingMode { get; set; } = RecordOverrideHandlingMode.Ignore;

    public HashSet<ModKey> PluginsWithOverrideRecords { get; set; } = new();
    public bool IncludeOutfits { get; set; } = false;
    public bool HasAlteredMergeLogic { get; set; } = false; 
    public ModStateSnapshot? LastKnownState { get; set; }
}