using System.Diagnostics;
using System.Windows.Media;
using Mutagen.Bethesda.Plugins;
using Newtonsoft.Json;
using NPC_Plugin_Chooser_2.View_Models;

namespace NPC_Plugin_Chooser_2.Models;

[DebuggerDisplay("{DisplayName}")]
public class ModSetting
{
    public string DisplayName { get; set; } = string.Empty;
    public List<ModKey> CorrespondingModKeys { get; set; } = new();
    public HashSet<ModKey> ResourceOnlyModKeys { get; set; } = new();
    public List<string> CorrespondingFolderPaths { get; set; } = new(); // first should be the base mod, and others are overrides where the program should find conflict winning data if it exists
    public List<string> MugShotFolderPaths { get; set; } = new();
    public bool IsFaceGenOnlyEntry { get; set; } = false;
    public HashSet<FormKey> FaceGenOnlyNpcFormKeys { get; set; } = new();
    public bool IsAutoGenerated { get; set; } = false;
    public HashSet<FormKey> NpcFormKeys { get; set; } = new(); // All NPCs contained in this mod
    public Dictionary<FormKey, List<ModKey>> AvailablePluginsForNpcs { get; set; } = new(); // Maps all available CorrespondingModKeys that can be used as a source plugin for this ModSetting
    public HashSet<FormKey> AmbiguousNpcFormKeys { get; set; } = new(); // All NPCs with > 1 available plugins
    public Dictionary<FormKey, ModKey> NpcPluginDisambiguation { get; set; } = new(); // Maps NPC FormKey to the ModKey from which it should inherit data, specifically for NPCs appearing in multiple plugins within this ModSetting.
    public Dictionary<FormKey, string> NpcFormKeysToDisplayName { get; set; } = new();

    public bool MergeInDependencyRecords { get; set; } = true;
    public bool HasAlteredMergeLogic { get; set; } = false; 
    public bool HandleInjectedRecords { get; set; } = false;
    public bool HasAlteredHandleInjectedRecordsLogic { get; set; } = false;
    public HashSet<string> Keywords { get; set; } = new();
    
    [JsonIgnore]
    public static string DefaultRecordInjectionToolTip =
        "If checked, the patcher will search for and merge in records that are injected. This can potentially make patching take longer.";
    public string HandleInjectedOverridesToolTip { get; set; } = DefaultRecordInjectionToolTip;

    [JsonIgnore] 
    public static string DefaultMergeInTooltip =
        "If checked, all records needed by the mod will be merged into the output." +
        Environment.NewLine + "The output plugin will no longer depend on them as masters." +
        Environment.NewLine + "Only masters found within this mod's Mod Folders will be merged in." +
        Environment.NewLine + "Do not merge in records from plugins that are going to be kept in your load order.";
    
    public string MergeInToolTip { get; set; } = DefaultMergeInTooltip;

    public RecordOverrideHandlingMode? ModRecordOverrideHandlingMode { get; set; } = RecordOverrideHandlingMode.Ignore;
    public int MaxNestedIntervalDepth { get; set; } = 2;
    public bool IncludeAllOverrides { get; set; } = false;
    public HashSet<ModKey> PluginsWithOverrideRecords { get; set; } = new();
    public bool IncludeOutfits { get; set; } = false;
    public bool CopyAssets { get; set; } = true;

    // Base-game-overwrite protection: some mods ship assets at the same data-relative paths as
    // base game / Creation Club assets (e.g. loose skin textures in overhauls like Cathedral HMB).
    // Copying those into the output would override the user's installed replacers (skin mods etc.)
    // game-wide, so the patcher skips them unless the user opts in per mod. FaceGen files are
    // exempt — they are inherently per-NPC and must live at their vanilla-derived paths.
    // OverwriteBaseGameAssets is the user's opt-in; HasBaseGameAssetPaths/BaseGameAssetPathCount
    // are the scan result (computed on import/refresh, not per launch) that controls whether the
    // checkbox is shown. The patcher-side skip is a live path test independent of the scan result.
    public bool OverwriteBaseGameAssets { get; set; } = false;
    public bool HasBaseGameAssetPaths { get; set; } = false;
    public int BaseGameAssetPathCount { get; set; } = 0;

    // Wig/antler detection results (computed during mod analysis on cache miss,
    // persisted so cache hits keep them — same lifecycle as HasBaseGameAssetPaths).
    // Wigs are detected from two sources:
    //   DetectedWigArmors        — ARMOs whose Name contains "wig"/"hair" AND whose
    //                              ARMA(s) occupy a hair biped slot (31 Hair /
    //                              41 LongHair), carried in an outfit.
    //   DetectedWigArmatures     — hair-slot ARMAs carried directly in an NPC's
    //                              WornArmor (WNAM; the High Poly NPC Overhaul
    //                              bald-FaceGen + skin-hair pattern), slot-first
    //                              NPC-scoped detection plus a keyword pass.
    //                              Manual is/is-not designations
    //                              (Settings.IsWigArmature) refine this set at
    //                              consumption time.
    // Antlers are detected from three sources so Remove can reach all of them:
    //   DetectedAntlerArmors     — ARMOs whose EditorID/Name contains "antler"
    //                              (in an outfit; no slot guard).
    //   DetectedAntlerArmatures  — ARMAs whose EditorID contains "antler" (baked
    //                              into a WornArmor) plus the addons of the antler
    //                              ARMOs above.
    //   DetectedAntlerHeadParts  — HeadParts whose Name/EditorID contains "antler"
    //                              (baked into the FaceGen).
    // ModWigHandlingMode / ModAntlerHandlingMode: per-mod overrides of the global
    // Settings.DefaultWigHandlingMode / DefaultAntlerHandlingMode (null = default).
    public HashSet<FormKey> DetectedWigArmors { get; set; } = new();
    public HashSet<FormKey> DetectedWigArmatures { get; set; } = new();
    public HashSet<FormKey> DetectedAntlerArmors { get; set; } = new();
    public HashSet<FormKey> DetectedAntlerArmatures { get; set; } = new();
    public HashSet<FormKey> DetectedAntlerHeadParts { get; set; } = new();
    public WigHandlingMode? ModWigHandlingMode { get; set; } = null;
    public AntlerHandlingMode? ModAntlerHandlingMode { get; set; } = null;

    [JsonIgnore]
    public bool HasWigArmors => DetectedWigArmors.Count > 0;

    /// <summary>Whether the analysis SCAN detected wigs from either source
    /// (outfit ARMOs or WNAM-carried hair ARMAs). User designations (persisted
    /// on <see cref="Settings.ManualWigArmatures"/>) are folded in by
    /// <see cref="Settings.ModHasWigs"/> — use that for effective checks.</summary>
    [JsonIgnore]
    public bool HasWigSources => DetectedWigArmors.Count > 0 || DetectedWigArmatures.Count > 0;

    /// <summary>Whether the analysis SCAN detected antlers (any of the three
    /// sources). User-designated antlers (persisted on
    /// <see cref="Settings.ManualAntlerHeadParts"/>) are folded in by
    /// <see cref="Settings.ModHasAntlers"/> — use that for effective checks.</summary>
    [JsonIgnore]
    public bool HasDetectedAntlers => DetectedAntlerArmors.Count > 0 ||
                                      DetectedAntlerArmatures.Count > 0 ||
                                      DetectedAntlerHeadParts.Count > 0;

    [JsonIgnore]
    public bool HasAntlers => HasDetectedAntlers;

    public Dictionary<FormKey, (NpcIssueType IssueType, string IssueMessage, FormKey? ReferencedFormKey)> 
        NpcFormKeysToNotifications
    {
        get;
        set;
    } = new();
    public ModStateSnapshot? LastKnownState { get; set; }
}